project:
  type: website
  resources:
    - "*.xlsx"
    - "*.xlsm"
    - "*.xls"
    - "*.pptx"

website:
  title: "SMDM Europe 2023"
  margin-footer: |
    ![](CHEMlogo_white.png)
  sidebar:
    style: "floating"
    search: false
    collapse-level: 2
    contents:
      - index.qmd
      - section: "Slides"
        contents:
          - text: Introduction 
            href: slides/00_welcome-and-intros.qmd
          - text: Mortality 
            href: slides/01_mortality.qmd
          - text: Embedding the Transition Matrix
            href: slides/02_competing-events.qmd
          - text: Advanced Bookkeeping
            href: slides/03_advanced-bookkeeping.qmd
          - text: Incorporating New Evidence
            href: slides/04_incorporating-new-evidence-and-uncertainty.qmd            
      - text: "Workshop Blog"
        href: blog/index.qmd            
      - text: Instructors 
        href: roster.qmd

execute:
  freeze: auto  # re-render only when source changes

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    grid:
      sidebar-width: 300px
      body-width: 1000px
      margin-width: 200px
      gutter-width: 1.5rem

editor: visual

