---
title: "What They Didn't Teach You About Decision Modeling"
subtitle: "SMDM 2023 - 18th Biennial European Conference"
editor: source
format:
  revealjs:
    transition: fade
    background-transition: fade
    incremental: true 
    footer: |
      [Back to Website](../index.html)
editor_options: 
  chunk_output_type: console
self-contained: true
bibliography: references.bib
---

## Welcome to Berlin!

- Introductions
- Workshop Learning Objectives
- Conceptual Framework 

## Workshop Overview

- "Bag of tricks" to fill the gaps in CEA modeling. 
- Primary focus is discrete time Markov, but much of the material is also useful for discrete event simulation and microsimulation modeling. 

## Workshop Overview 

- Our primary aim is to provide you with intuition for why to use these methods.
- We also aim to provide you with code.
- We'll move fast; don't worry if everything doesn't immediately resonate!

## Learning Objectives (Morning)

1. Fit a parametric mortality model to life table data to:
    - Net out cause-specific death from overall mortality (i.e., *truly* model background mortality).
    -  Accurately simulate death times in a discrete event model.
    - Summarize background mortality for a discrete time Markov model in a few parameters. 
    
## Learning Objectives (Morning)

2. Accurately construct a transition probability matrix.
  - The rate-to-probability (and probability-to-rate) conversion formulas you probably learned are technically correct, but only in a very narrow case with **no** competing risks like death.

## Learning Objectives (Afternoon)

3. Include non-markovian matrix elements to capture:

    -  Counts of total events or counts of event transitions (single cycle) to/from certain states (e.g., how to deal with one-time costs).
    -  Tunnel states to capture transitory health and/or cost dynamics.
    
## Learning Objectives (Afternoon)

4. Backwards-convert an existing Markov model 
  - Facilitates adapation of existing models to accommodate new evidence, strategies, additional health states, different cycle lengths, etc.

## Learning Objectives (Afternoon)

5. Solve for PSA distribution parameters given sparse information from the literature (e.g., IQR of costs of $300-$750).

6. Improve the efficiency of PSA analyses by sampling correlated PSA distributions using copulas.


# Conceptual Framework 

## What They Taught You is (Technically) Wrong

- A lot of the common methods taught for CEA are shortcuts, or may be technically correct for narrow cases---but are not generally.

- This doesn't mean everything published is totally wrong, however.

- Because we often make comparisons across strategies, errors may (approximately) cancel out. 
  - There is no guarantee of this, however. 

## The Big Picture

-   Decision thresholds methods, e.g. ICER, NMB, NHB all involve comparing a model run versus a reference run of the same model.
-   For example, a model of $f_{cost}$ and $f_{qaly}$ are run versus $\theta_{ref}$ and $\theta_{target}$.
-   These runs will have error due to misspecification, and in differencing the error can mostly cancel. Let $g$ represent the truth, thus $f(\theta) = g(\theta)+\epsilon_{\theta}$.

## The Hopeful Big Picture

$$\text{ICER} = \frac{f_{cost}(\theta_{target}) - \epsilon_{ct} - f_{cost}(\theta_{ref}) + \epsilon_{cr}}{f_{qaly}(\theta_{target}) - \epsilon_{qt} - f_{qaly}(\theta_{ref}) + \epsilon_{qr}}$$

-   If $\epsilon_{ct} \sim \epsilon_{cr}$ and $\epsilon_{qt} \sim \epsilon_{qr}$ then the model errors cancel and this approaches the true model.
-   The decision threshold is *robust* in this case even when model run results are biased!

## The Hopeful Big Picure

-   A similar theme will occur periodically today. 
- We'll aim to highlight when these issues may be decision-relevant (i.e., errors may not cancel)

## Questions?
