---
title: "Incorporating New Evidence and Uncertainty"
subtitle: "Solving for PSA Parameters and Copula-Based PSA Sampling"
editor: source
format:
  revealjs:
    transition: fade
    background-transition: fade
    incremental: true 
    footer: |
      [Back to Website](../index.html)
editor_options: 
  chunk_output_type: console
self-contained: true
bibliography: references.bib
---

```{r setup}
source("./manifest.r")
```

## Scenario

- Your model has a rate `rH_CVD` and you want to define a probabilistic sensitivity analysis (PSA) distribution around it.


## ParameterSolver

- [Link](https://biostatistics.mdanderson.org/SoftwareDownload/SingleSoftware/Index/6)

## Common PSA Distributions

| Parameter Type                  | Distribution     |
|---------------------------------|------------------|
| Probability                     | beta             |
| Rate                            | gamma            |
| Utility weight                  | beta             |
| Right skew (e.g., cost)         | gamma, lognormal |
| Relative risks or hazard ratios | lognormal        |
| Odds Ratio                      | logistic         |


# Copulas

## What is a Copula?

-   The binding "glue" between correlated variables.
-   

## Copulas and PSA Sampling {auto-animate="true"}

We typically draw PSA samples from the *marginal* distribution of each variable:

$$
F_1(x_1),  ..., F_d(x_d)
$$

## Copulas and PSA Sampling {auto-animate="true"}

Copulas allow us to sample from the *joint* distribution:

$$
F(x_1,...,x_d) = C \big ( F_1(x_1), ..., F_d(x_d) \big )
$$

(This is a result of Sklar \[1959\].)

## Copulas and PSA Sampling {auto-animate="true"}

-   Copula: a multivariate cumulative distribution function with uniform marginals.
