library(tidyverse)
library(knitr)
library(kableExtra)
library(survival)
library(flexsurv)
library(haven)
library(dampack)
library(Matrix)
library(here)
library(demography)
library(MortalityLaws)
library(demography)
library(MASS)
library(directlabels)
library(ggthemes)
library(expm)
library(gt)
library(directlabels)
library(glue)
library(ggsci)
theme_set(hrbrthemes::theme_ipsum(base_family = "Arial"))


options("scipen" = 100, "digits" = 5)

select <- dplyr::select