{
  "hash": "907391e306a2a608110dac86d471745a",
  "result": {
    "markdown": "---\ntitle: \"Embedding A Transition Probability Matrix for a Discrete Time Markov Model\"\neditor: visual\neditor_options: \n  chunk_output_type: console\nexecute: \n  cache: false\n---\n\n\n# Prologue\n\nDefine $r_{HS}$ and $r_{HD}$ as the hazard rate of two independent competing risks from a given (Healthy) health state (to Sick and Dead, respectively), and $\\Delta t$ the cycle length (e.g., $1$=1 year, $1/12$=1 month, etc.). We can also define a third rate $r_{SD} = hr_{S}*r_{HD}$ for transitioning from sick to dead, i.e., the standard (healthy-to-dead) rate multiplied by the hazard ratio $hr_{S}$.\n\nThe underlying Markov model takes the following form:\n\n\n::: {.cell}\n\n:::\n\n\n::: column-page\n\n```{dot}\n//| fig-align: center\n//| fig-width: 4\n//| fig-cap: Model Diagram\n//| label: fig-model\n\ndigraph G {\n    layout = neato;\n    Healthy [pos=\"0,0!\"];\n    Sick [pos=\"1,1!\"]; \n    Dead [pos=\"1,-1!\"]\n    Healthy -> Healthy ;\n    Sick -> Sick;\n    Healthy -> Sick [label=\"r_HS\"]; \n    Sick -> Dead [label=\"hr_S * r_HD\"];\n    Healthy -> Dead [label=\"r_HD\"];\n    Dead -> Dead ;\n  }\n```\n\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nlibrary(Matrix)\nlibrary(tidyverse)\nlibrary(expm)\nlibrary(knitr)\nlibrary(gt)\nlibrary(directlabels)\nlibrary(glue)\nlibrary(ggsci)\nlibrary(ggthemes)\n\n# Better accuracy that \"life-table\" aka trapezoidal method\nalt_simp_coef <- function(i) c(17, 59, 43, 49, rep(48, i-8), 49, 43, 59, 17) / 48\nalt_simp      <- function(x,h) h*sum(alt_simp_coef(length(x)) * x)\n\nr_HS <- 0.15\nr_HD <- .006\nhr_S <- 10\nr_SD <- hr_S*r_HD\ncycle <- 1\n\n# 1-exp(-r_HS*cycle)\n# 1-exp(-r_HD*cycle)\n\nget_P <- function(r_HS,r_HD,r_SD,cycle) {\n  P_st <- \n  matrix(\n  c(exp(-r_HS*cycle) + exp(-r_HD*cycle) -1 ,  (1-exp(-r_HS*cycle)) ,  1-exp(-r_HD*cycle), \n  0, exp(-r_SD*cycle), 1-exp(-r_SD*cycle),\n  0,0,1),\n  nrow = 3, \n  ncol = 3,\n  byrow=TRUE,\n  dimnames = list(c(\"Healthy\",\"Sick\",\"Dead\"), c(\"Healthy\",\"Sick\",\"Dead\"))\n  ) %>% \n    data.frame() %>% \n    rownames_to_column(var = \"from\") %>% \n    mutate(name = \"P_st\")\n\n  P_eQ <- matrix(\n    c(-(r_HS*cycle+r_HD*cycle),r_HS*cycle,r_HD*cycle,\n      0,-r_SD*cycle,r_SD*cycle,\n      0,0,0),\n      nrow=3,\n      ncol=3,\n      byrow=TRUE,\n    dimnames = list(c(\"Healthy\",\"Sick\",\"Dead\"), c(\"Healthy\",\"Sick\",\"Dead\"))\n  ) %>% expm() %>% as.matrix() %>% \n    data.frame() %>% \n    rownames_to_column(var = \"from\") %>% \n    mutate(name = \"P_eQ\")\n\n\n  P_cr <- \n    matrix(\n    c(exp(-(r_HS+r_HD)*cycle) , (r_HS/(r_HS+r_HD)) * (1-exp(-(r_HS+r_HD)*cycle))   ,(r_HD/(r_HS+r_HD)) * (1-exp(-(r_HS+r_HD)*cycle))   , \n    0, exp(-r_SD*cycle), 1-exp(-r_SD*cycle),\n    0,0,1),\n    nrow = 3, \n    ncol = 3,\n    byrow=TRUE,\n    dimnames = list(c(\"Healthy\",\"Sick\",\"Dead\"), c(\"Healthy\",\"Sick\",\"Dead\"))\n  ) %>% \n    data.frame() %>% \n    rownames_to_column(var = \"from\") %>% mutate(name = \"P_cr\")\n  \n  \n  \n  out <- bind_rows( P_st, P_cr , P_eQ)\n  return(out)\n}\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\ncheck_sens <- function(r_HD,r_HS,r_SD,cycle) {\n  \nQ <- matrix(\n    c(-(r_HS*cycle+r_HD*cycle),r_HS*cycle,r_HD*cycle,\n      0,-r_SD*cycle,r_SD*cycle,\n      0,0,0),\n      nrow=3,\n      ncol=3,\n      byrow=TRUE,\n    dimnames = list(c(\"Healthy\",\"Sick\",\"Dead\"), c(\"Healthy\",\"Sick\",\"Dead\"))\n  ) \n\n# Q_ <- rbind(cbind(Q,c(r_HS*cycle,0,0)),c(0,0,0,0)) \n# Q_ <- rbind(cbind(Q_,c(r_HD*cycle,0,0,0)),c(0,0,0,0,0))\n# dimnames(Q_) = list(c(\"Healthy\",\"Sick\",\"Dead\",\"accS\",\"accHD\"),\n#                    c(\"Healthy\",\"Sick\",\"Dead\",\"accS\",\"accHD\"))\n\nQ_ <- Q\n\nP <- Q_ %>% expm() %>% as.matrix() \nres <- get_P(r_HS=r_HS,r_HD=r_HD,r_SD=r_SD,cycle=cycle)\n\nP_cr <- res %>% filter(name==\"P_cr\") %>% select(from,Healthy,Sick,Dead) %>% \n  data.frame() %>% \n  column_to_rownames(var = \"from\") %>% \n  as.matrix()\n\nP_st <- res %>% filter(name==\"P_st\") %>% select(from,Healthy,Sick,Dead) %>% \n  data.frame() %>% \n  column_to_rownames(var = \"from\") %>% \n  as.matrix()\n\nle1 <- \n  0:(60/cycle) %>% map(~(c(1000,0,0) %*% (P[1:3,1:3] %^% (.x)))) %>% \n  map(~(.x %>% data.frame)) %>% \n  bind_rows() %>% \n  as.matrix() %>%  \n  {.[,-3]} %>% \n  alt_simp(.,1) %>% \n  {. * cycle} %>% {./1000} %>% \n  data.frame() %>% \n  set_names(\"life_exp\")\n\nres1 <- 0:(60/cycle) %>% map_df(~(c(1000,0,0) %*% (P %^%.x) %>% data.frame())) %>% \n  mutate(cycle = 0:(60/cycle)) %>% \n  select(cycle, everything()) %>% \n  tibble() %>% \n  tail(n=1) %>% \n  bind_cols(le1) %>% \n  mutate(method = \"P_eQ\") \n\nle2 <- \n  0:(60/cycle) %>% map(~(c(1000,0,0) %*% (P_cr[1:3,1:3] %^% (.x)))) %>% \n  map(~(.x %>% data.frame)) %>% \n  bind_rows() %>% \n   as.matrix() %>%  \n  {.[,-3]} %>% \n  alt_simp(.,1) %>% \n  {. * cycle} %>% {./1000} %>% \n  data.frame() %>% \n  set_names(\"life_exp\")\n  \nres2 <- 0:(60/cycle) %>% map_df(~(c(1000,0,0) %*% (P_cr %^%.x) %>% data.frame())) %>% \n  mutate(cycle = 0:(60/cycle)) %>% \n  select(cycle, everything()) %>% \n  tibble() %>% \n  tail(n=1) %>% \n  bind_cols(le2) %>% \n  mutate(method = \"P_cr\")\n\n\nle3 <- \n 0:(60/cycle) %>% map(~(c(1000,0,0) %*% (P_st[1:3,1:3] %^% (.x)))) %>% \n  map(~(.x %>% data.frame)) %>% \n  bind_rows() %>% \n   as.matrix() %>%  \n  {.[,-3]} %>% \n  alt_simp(.,1) %>% \n  {. * cycle} %>% {./1000} %>% \n  data.frame() %>% \n  set_names(\"life_exp\")\n\nres3 <- 0:(60/cycle) %>% map_df(~(c(1000,0,0) %*% (P_st %^%.x) %>% data.frame())) %>% \n  mutate(cycle = 0:(60/cycle)) %>% \n  select(cycle, everything()) %>% \n  tibble() %>% \n  tail(n=1) %>% \n  bind_cols(le3) %>% \n  mutate(method = \"P_st\")\n  \n  out <- res1 %>% bind_rows(res2) %>% bind_rows(res3)\n  return(out)\n\n}\n```\n:::\n\n\n# Act 1: A World Without Death\n\nIt's useful to begin with a completely unrealistic scenario: there is essentially no death. That is, individuals can either be Healthy or Sick, but they do not die. Furthermore, as shown in @fig-model, once someone becomes sick, they are chronically ill and can not transition back to death.\n\nLet's set the model parameters as follows. Essentially what we're doing is setting the death rate(`r_HD)` to an extraordinarily small number (`0.00000001)`\n\n| param | value                         |\n|-------|-------------------------------|\n| r_HS  | 0.15        |\n| r_HD  | 10^{-8}  |\n| hr_S  | 10          |\n| r_SD  | 10^{-7} |\n\nIt is common to use the following formula to convert rates to probabilities:\n\n$$\np_{HS}= 1 - e^{-r_{HS}\\Delta t} \n$$\n\nApplying this to our example, the probability of transitioning from healthy to sick in a single one-year cycle is\n\n$$\np_{HD} = 1 - e^{-0.15} = 0.139292\n$$\n\nAfter 2 years (1-year cycle), and assuming there is essentially no death at all in a starting cohort of 1,000 individuals, how many people would we expect to be in the sick state?\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nc(1000,0) %*% \n  (matrix(c(exp(-.15),1-exp(-.15),0,1), nrow=2,ncol=2,byrow = TRUE,\n                   dimnames=list(c(\"Healthy\",\"Sick\"),c(\"Healthy\",\"Sick\"))) %^% 2) %>% \n  data.frame() %>% \n  gt()\n```\n\n::: {#fig-nodeath1y .cell-output-display}\n```{=html}\n<div id=\"alwcwimtsg\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>html {\n  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n}\n\n#alwcwimtsg .gt_table {\n  display: table;\n  border-collapse: collapse;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#alwcwimtsg .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#alwcwimtsg .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#alwcwimtsg .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#alwcwimtsg .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 0;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#alwcwimtsg .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#alwcwimtsg .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#alwcwimtsg .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#alwcwimtsg .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#alwcwimtsg .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#alwcwimtsg .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#alwcwimtsg .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#alwcwimtsg .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#alwcwimtsg .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#alwcwimtsg .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#alwcwimtsg .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#alwcwimtsg .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#alwcwimtsg .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#alwcwimtsg .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#alwcwimtsg .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#alwcwimtsg .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#alwcwimtsg .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#alwcwimtsg .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#alwcwimtsg .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#alwcwimtsg .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#alwcwimtsg .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#alwcwimtsg .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#alwcwimtsg .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#alwcwimtsg .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#alwcwimtsg .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-left: 4px;\n  padding-right: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#alwcwimtsg .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#alwcwimtsg .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#alwcwimtsg .gt_left {\n  text-align: left;\n}\n\n#alwcwimtsg .gt_center {\n  text-align: center;\n}\n\n#alwcwimtsg .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#alwcwimtsg .gt_font_normal {\n  font-weight: normal;\n}\n\n#alwcwimtsg .gt_font_bold {\n  font-weight: bold;\n}\n\n#alwcwimtsg .gt_font_italic {\n  font-style: italic;\n}\n\n#alwcwimtsg .gt_super {\n  font-size: 65%;\n}\n\n#alwcwimtsg .gt_footnote_marks {\n  font-style: italic;\n  font-weight: normal;\n  font-size: 75%;\n  vertical-align: 0.4em;\n}\n\n#alwcwimtsg .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#alwcwimtsg .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#alwcwimtsg .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#alwcwimtsg .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#alwcwimtsg .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#alwcwimtsg .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\">\n  \n  <thead class=\"gt_col_headings\">\n    <tr>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Healthy\">Healthy</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Sick\">Sick</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Healthy\" class=\"gt_row gt_right\">740.8182</td>\n<td headers=\"Sick\" class=\"gt_row gt_right\">259.1818</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n\nState Occpancy with No Death\n:::\n:::\n\n\nLet's also calculate total life expectancy to make sure everything is running smoothly. We'll also ignore any discounting in the life expectancy calculation.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\ntr <- \n  0:60 %>% map(~({\n  c(1000,0) %*% \n    (matrix(c(exp(-.15),1-exp(-.15),0,1), nrow=2,ncol=2,byrow = TRUE,\n                   dimnames=list(c(\"Healthy\",\"Sick\"),c(\"Healthy\",\"Sick\"))) %^% .x) \n  }))  %>% \n  map(~(.x %>% data.frame())) %>% \n  bind_rows()\n\np <- matrix(c(1,1),nrow=2)\n\n\nlife_exp_nodeath  <- data.frame(life_exp = as.matrix(tr) %>% \n  alt_simp(.,1) %>% \n  {. * cycle} %>% {./1000} ) %>% \n  {round(.,1)}\n\nlife_exp_nodeath %>% \n  gt() %>% \n  cols_label(\"life_exp\"=\"Total Life Expectancy\") %>% \n  tab_source_note(\"Note that we are ignoring discounting\")\n```\n\n::: {#fig-lifeexp-nodeath .cell-output-display}\n```{=html}\n<div id=\"qkkzryyalu\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>html {\n  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n}\n\n#qkkzryyalu .gt_table {\n  display: table;\n  border-collapse: collapse;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#qkkzryyalu .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#qkkzryyalu .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#qkkzryyalu .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#qkkzryyalu .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 0;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#qkkzryyalu .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qkkzryyalu .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#qkkzryyalu .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#qkkzryyalu .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#qkkzryyalu .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#qkkzryyalu .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#qkkzryyalu .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#qkkzryyalu .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#qkkzryyalu .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#qkkzryyalu .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#qkkzryyalu .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#qkkzryyalu .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#qkkzryyalu .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qkkzryyalu .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#qkkzryyalu .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#qkkzryyalu .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qkkzryyalu .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#qkkzryyalu .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#qkkzryyalu .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qkkzryyalu .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qkkzryyalu .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#qkkzryyalu .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#qkkzryyalu .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qkkzryyalu .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#qkkzryyalu .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-left: 4px;\n  padding-right: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qkkzryyalu .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#qkkzryyalu .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qkkzryyalu .gt_left {\n  text-align: left;\n}\n\n#qkkzryyalu .gt_center {\n  text-align: center;\n}\n\n#qkkzryyalu .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#qkkzryyalu .gt_font_normal {\n  font-weight: normal;\n}\n\n#qkkzryyalu .gt_font_bold {\n  font-weight: bold;\n}\n\n#qkkzryyalu .gt_font_italic {\n  font-style: italic;\n}\n\n#qkkzryyalu .gt_super {\n  font-size: 65%;\n}\n\n#qkkzryyalu .gt_footnote_marks {\n  font-style: italic;\n  font-weight: normal;\n  font-size: 75%;\n  vertical-align: 0.4em;\n}\n\n#qkkzryyalu .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#qkkzryyalu .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#qkkzryyalu .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#qkkzryyalu .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#qkkzryyalu .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#qkkzryyalu .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\">\n  \n  <thead class=\"gt_col_headings\">\n    <tr>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Total Life Expectancy\">Total Life Expectancy</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"life_exp\" class=\"gt_row gt_right\">60</td></tr>\n  </tbody>\n  <tfoot class=\"gt_sourcenotes\">\n    <tr>\n      <td class=\"gt_sourcenote\" colspan=\"1\">Note that we are ignoring discounting</td>\n    </tr>\n  </tfoot>\n  \n</table>\n</div>\n```\n\n\nTotal Life Expectancy in a Scenario with No Death (or Discounting)\n:::\n:::\n\n\nNot surprisingly, when there is no death or discounting, over a 60 year horizon life expectancy is 60.\n\nFinally, let's make one more tweak and switch from a yearly to a monthly time cycle. Again, we find identical answers for both the total number who become sick (after 2 years), and for life expectancy.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nc(1000,0) %*% \n  (matrix(c(exp(-.15 * (1/12)),1-exp(-.15 * (1/12)),0,1), nrow=2,ncol=2,byrow = TRUE,\n                   dimnames=list(c(\"Healthy\",\"Sick\"),c(\"Healthy\",\"Sick\"))) %^% (2/(1/12))) %>% \n  data.frame() %>% \n  gt()\n```\n\n::: {#fig-nodeathdaily .cell-output-display}\n```{=html}\n<div id=\"vndjipjcsk\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>html {\n  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n}\n\n#vndjipjcsk .gt_table {\n  display: table;\n  border-collapse: collapse;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#vndjipjcsk .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#vndjipjcsk .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#vndjipjcsk .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#vndjipjcsk .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 0;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#vndjipjcsk .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vndjipjcsk .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#vndjipjcsk .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#vndjipjcsk .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#vndjipjcsk .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#vndjipjcsk .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#vndjipjcsk .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#vndjipjcsk .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#vndjipjcsk .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#vndjipjcsk .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#vndjipjcsk .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#vndjipjcsk .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#vndjipjcsk .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vndjipjcsk .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#vndjipjcsk .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#vndjipjcsk .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vndjipjcsk .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#vndjipjcsk .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#vndjipjcsk .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vndjipjcsk .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vndjipjcsk .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#vndjipjcsk .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#vndjipjcsk .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vndjipjcsk .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#vndjipjcsk .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-left: 4px;\n  padding-right: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vndjipjcsk .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#vndjipjcsk .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vndjipjcsk .gt_left {\n  text-align: left;\n}\n\n#vndjipjcsk .gt_center {\n  text-align: center;\n}\n\n#vndjipjcsk .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#vndjipjcsk .gt_font_normal {\n  font-weight: normal;\n}\n\n#vndjipjcsk .gt_font_bold {\n  font-weight: bold;\n}\n\n#vndjipjcsk .gt_font_italic {\n  font-style: italic;\n}\n\n#vndjipjcsk .gt_super {\n  font-size: 65%;\n}\n\n#vndjipjcsk .gt_footnote_marks {\n  font-style: italic;\n  font-weight: normal;\n  font-size: 75%;\n  vertical-align: 0.4em;\n}\n\n#vndjipjcsk .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#vndjipjcsk .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#vndjipjcsk .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#vndjipjcsk .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#vndjipjcsk .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#vndjipjcsk .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\">\n  \n  <thead class=\"gt_col_headings\">\n    <tr>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Healthy\">Healthy</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Sick\">Sick</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Healthy\" class=\"gt_row gt_right\">740.8182</td>\n<td headers=\"Sick\" class=\"gt_row gt_right\">259.1818</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n\nState Occpancy with No Death\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\ntr <- \n  0:(60*12) %>% map(~({\n  c(1000,0) %*% \n    (matrix(c(exp(-.15/12),1-exp(-.15/12),0,1), nrow=2,ncol=2,byrow = TRUE,\n                   dimnames=list(c(\"Healthy\",\"Sick\"),c(\"Healthy\",\"Sick\"))) %^% .x) \n  }))  %>% \n  map(~(.x %>% data.frame())) %>% \n  bind_rows()\n\np <- matrix(c(1,1),nrow=2)\n\nlife_exp_nodeath  <- data.frame(life_exp = as.matrix(tr) %>% \n  alt_simp(.,1) %>% \n  {. * (1/12)} %>% {./1000} ) %>% \n  {round(.,1)}\n\nlife_exp_nodeath %>% \n  gt() %>% \n  cols_label(\"life_exp\"=\"Total Life Expectancy\") %>% \n  tab_source_note(\"Note that we are ignoring discounting\")\n```\n\n::: {#fig-lifeexp-nodeath-monthly .cell-output-display}\n```{=html}\n<div id=\"kvjhdhsphf\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>html {\n  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n}\n\n#kvjhdhsphf .gt_table {\n  display: table;\n  border-collapse: collapse;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#kvjhdhsphf .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#kvjhdhsphf .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#kvjhdhsphf .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#kvjhdhsphf .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 0;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#kvjhdhsphf .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#kvjhdhsphf .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#kvjhdhsphf .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#kvjhdhsphf .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#kvjhdhsphf .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#kvjhdhsphf .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#kvjhdhsphf .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#kvjhdhsphf .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#kvjhdhsphf .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#kvjhdhsphf .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#kvjhdhsphf .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#kvjhdhsphf .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#kvjhdhsphf .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kvjhdhsphf .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#kvjhdhsphf .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#kvjhdhsphf .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kvjhdhsphf .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#kvjhdhsphf .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#kvjhdhsphf .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#kvjhdhsphf .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kvjhdhsphf .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#kvjhdhsphf .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#kvjhdhsphf .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#kvjhdhsphf .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#kvjhdhsphf .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-left: 4px;\n  padding-right: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kvjhdhsphf .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#kvjhdhsphf .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kvjhdhsphf .gt_left {\n  text-align: left;\n}\n\n#kvjhdhsphf .gt_center {\n  text-align: center;\n}\n\n#kvjhdhsphf .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#kvjhdhsphf .gt_font_normal {\n  font-weight: normal;\n}\n\n#kvjhdhsphf .gt_font_bold {\n  font-weight: bold;\n}\n\n#kvjhdhsphf .gt_font_italic {\n  font-style: italic;\n}\n\n#kvjhdhsphf .gt_super {\n  font-size: 65%;\n}\n\n#kvjhdhsphf .gt_footnote_marks {\n  font-style: italic;\n  font-weight: normal;\n  font-size: 75%;\n  vertical-align: 0.4em;\n}\n\n#kvjhdhsphf .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#kvjhdhsphf .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#kvjhdhsphf .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#kvjhdhsphf .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#kvjhdhsphf .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#kvjhdhsphf .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\">\n  \n  <thead class=\"gt_col_headings\">\n    <tr>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Total Life Expectancy\">Total Life Expectancy</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"life_exp\" class=\"gt_row gt_right\">60</td></tr>\n  </tbody>\n  <tfoot class=\"gt_sourcenotes\">\n    <tr>\n      <td class=\"gt_sourcenote\" colspan=\"1\">Note that we are ignoring discounting</td>\n    </tr>\n  </tfoot>\n  \n</table>\n</div>\n```\n\n\nMonthly Life Cycle - Total Life Expectancy in a Scenario with No Death (or Discounting)\n:::\n:::\n\n\n# Act 2: Here Be (Competing Risks) Dragons\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nres <- c(1000,0) %*% \n  (matrix(c(exp(-.15 * (1/12)),1-exp(-.15 * (1/12)),0,1), nrow=2,ncol=2,byrow = TRUE,\n                   dimnames=list(c(\"Healthy\",\"Sick\"),c(\"Healthy\",\"Sick\"))) %^% (2/(1/12)))\n```\n:::\n\n\nWith the knowledge that in a world without death, approximately 259 people would become ill after 2 years, and would expect to live for 60 years on average, what happens when we introduce death as a competing risk?\n\nLet's now set the background mortality rate $r_{HD}$ to 0.006. Let's also assume that the hazard rate for death among sick people is 10 times the death rate of healthy people (i.e., $r_{SD} = 10 \\cdot r_{HD}$).\n\nNote that death is only a competing risk for the Healthy state, since if someone is sick, death is the only other state they can transition out to:\n\n\n```{dot}\n//| fig-align: center\n//| fig-width: 4\ndigraph G {\n    layout = neato;\n    Healthy [pos=\"0,0!\"];\n    Sick [pos=\"1,1!\"]; \n    Dead [pos=\"1,-1!\"]\n    Healthy -> Healthy;\n    Sick -> Sick;\n    Healthy -> Sick [color=\"red\"]; \n    Sick -> Dead;\n    Healthy -> Dead [color=\"red\"];\n    Dead -> Dead;\n  }\n```\n\n\n## Standard Rate-to-Transition Conversion\n\nLet's first convert the supplied rates to probabilities using the same standard formulas, as above:\n\n$$\np_{HS}= 1 - e^{-r_{HS}\\cdot \\Delta t} \n$$\n\n$$\np_{HD} = 1 - e^{-r_{HD}\\cdot \\Delta t}\n$$\n\nWe can also define the probability of remaining healthy (i.e., transitioning to *neither* the sick or dead state) as:\n\n$$\np_{HH} = 1 - p_{HS} - p_{HD}= e^{-r_{HS}\\Delta t}  + e^{-r_{HD}\\Delta t} - 1\n$$\n\nAnd finally the probability of dying among sick people is defined as\n\n$$\np_{SD} = 1 - e^{-hr_{HD}\\cdot r_{HD}\\cdot \\Delta t}\n$$\n\n@fig-m_P-st shows the corresponding transition probability matrix:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nr_HD <- 0.006\nr_SD <- 10*0.006\n\nget_P(r_HS=r_HS,r_HD=r_HD,r_SD=r_SD,cycle=cycle) %>% \nfilter(name==\"P_st\") %>% \nselect(-name) %>% \n#column_to_rownames(\"from\") %>% \nmutate_at(vars(-from), ~round(.,4)) %>% \ngt() %>% \n  cols_label(\"from\"=\"\")\n```\n\n::: {#fig-m_P-st .cell-output-display}\n```{=html}\n<div id=\"zovlpupyxo\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>html {\n  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n}\n\n#zovlpupyxo .gt_table {\n  display: table;\n  border-collapse: collapse;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#zovlpupyxo .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#zovlpupyxo .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#zovlpupyxo .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#zovlpupyxo .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 0;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#zovlpupyxo .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zovlpupyxo .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#zovlpupyxo .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#zovlpupyxo .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#zovlpupyxo .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#zovlpupyxo .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#zovlpupyxo .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#zovlpupyxo .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#zovlpupyxo .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#zovlpupyxo .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#zovlpupyxo .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#zovlpupyxo .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#zovlpupyxo .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zovlpupyxo .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#zovlpupyxo .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#zovlpupyxo .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zovlpupyxo .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#zovlpupyxo .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#zovlpupyxo .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zovlpupyxo .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zovlpupyxo .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#zovlpupyxo .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#zovlpupyxo .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zovlpupyxo .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#zovlpupyxo .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-left: 4px;\n  padding-right: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zovlpupyxo .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#zovlpupyxo .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zovlpupyxo .gt_left {\n  text-align: left;\n}\n\n#zovlpupyxo .gt_center {\n  text-align: center;\n}\n\n#zovlpupyxo .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#zovlpupyxo .gt_font_normal {\n  font-weight: normal;\n}\n\n#zovlpupyxo .gt_font_bold {\n  font-weight: bold;\n}\n\n#zovlpupyxo .gt_font_italic {\n  font-style: italic;\n}\n\n#zovlpupyxo .gt_super {\n  font-size: 65%;\n}\n\n#zovlpupyxo .gt_footnote_marks {\n  font-style: italic;\n  font-weight: normal;\n  font-size: 75%;\n  vertical-align: 0.4em;\n}\n\n#zovlpupyxo .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#zovlpupyxo .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#zovlpupyxo .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#zovlpupyxo .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#zovlpupyxo .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#zovlpupyxo .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\">\n  \n  <thead class=\"gt_col_headings\">\n    <tr>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"\"></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Healthy\">Healthy</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Sick\">Sick</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Dead\">Dead</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"from\" class=\"gt_row gt_left\">Healthy</td>\n<td headers=\"Healthy\" class=\"gt_row gt_right\">0.8547</td>\n<td headers=\"Sick\" class=\"gt_row gt_right\">0.1393</td>\n<td headers=\"Dead\" class=\"gt_row gt_right\">0.0060</td></tr>\n    <tr><td headers=\"from\" class=\"gt_row gt_left\">Sick</td>\n<td headers=\"Healthy\" class=\"gt_row gt_right\">0.0000</td>\n<td headers=\"Sick\" class=\"gt_row gt_right\">0.9418</td>\n<td headers=\"Dead\" class=\"gt_row gt_right\">0.0582</td></tr>\n    <tr><td headers=\"from\" class=\"gt_row gt_left\">Dead</td>\n<td headers=\"Healthy\" class=\"gt_row gt_right\">0.0000</td>\n<td headers=\"Sick\" class=\"gt_row gt_right\">0.0000</td>\n<td headers=\"Dead\" class=\"gt_row gt_right\">1.0000</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n\nTransition Probability Matrix Using Standard Rate-to-Probability Conversion Formulas\n:::\n:::\n\n\nGiven this transition probability matrix, how many healthy, sick and dead individuals do we have in our cohort after a 60-year time horizon? @fig-60y-st summarizes state occupancy at the end of 60 years:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nres_60yst <- \n  check_sens(r_HD= r_HD, r_HS = r_HS, r_SD = r_SD, cycle=1) %>% \n  filter(method==\"P_st\") \nres_60yst %>% \n  select(cycle,Healthy,Sick,Dead,life_exp) %>% \n  gt::gt() %>% \n  sub_missing(missing_text=\"-\") %>% \n  fmt_number(columns = c(Healthy,Sick,Dead,life_exp),decimals=1) %>% \n  cols_label(\"life_exp\" = \"Life Expectancy\")\n```\n\n::: {#fig-60y-st .cell-output-display}\n```{=html}\n<div id=\"ehjastmmfn\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>html {\n  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n}\n\n#ehjastmmfn .gt_table {\n  display: table;\n  border-collapse: collapse;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ehjastmmfn .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ehjastmmfn .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ehjastmmfn .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ehjastmmfn .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 0;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ehjastmmfn .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ehjastmmfn .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ehjastmmfn .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ehjastmmfn .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ehjastmmfn .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ehjastmmfn .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ehjastmmfn .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ehjastmmfn .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ehjastmmfn .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ehjastmmfn .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ehjastmmfn .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ehjastmmfn .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ehjastmmfn .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ehjastmmfn .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ehjastmmfn .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ehjastmmfn .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ehjastmmfn .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ehjastmmfn .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ehjastmmfn .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ehjastmmfn .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ehjastmmfn .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ehjastmmfn .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ehjastmmfn .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ehjastmmfn .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ehjastmmfn .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-left: 4px;\n  padding-right: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ehjastmmfn .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ehjastmmfn .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ehjastmmfn .gt_left {\n  text-align: left;\n}\n\n#ehjastmmfn .gt_center {\n  text-align: center;\n}\n\n#ehjastmmfn .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ehjastmmfn .gt_font_normal {\n  font-weight: normal;\n}\n\n#ehjastmmfn .gt_font_bold {\n  font-weight: bold;\n}\n\n#ehjastmmfn .gt_font_italic {\n  font-style: italic;\n}\n\n#ehjastmmfn .gt_super {\n  font-size: 65%;\n}\n\n#ehjastmmfn .gt_footnote_marks {\n  font-style: italic;\n  font-weight: normal;\n  font-size: 75%;\n  vertical-align: 0.4em;\n}\n\n#ehjastmmfn .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ehjastmmfn .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ehjastmmfn .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ehjastmmfn .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ehjastmmfn .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ehjastmmfn .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\">\n  \n  <thead class=\"gt_col_headings\">\n    <tr>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"cycle\">cycle</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Healthy\">Healthy</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Sick\">Sick</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Dead\">Dead</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Life Expectancy\">Life Expectancy</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"cycle\" class=\"gt_row gt_right\">60</td>\n<td headers=\"Healthy\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"Sick\" class=\"gt_row gt_right\">43.6</td>\n<td headers=\"Dead\" class=\"gt_row gt_right\">956.3</td>\n<td headers=\"life_exp\" class=\"gt_row gt_right\">22.1</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n\n1-Year Cycle\n:::\n:::\n\n\nAs @fig-60y-st shows, after 60 years, 43.6 are recorded as being in the sick state and life expectancy has reduced to 22.1 years.\n\nAs above, let's now repeat the same exercise using a *daily* cycle length:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nres_60yst_daily <- \n  check_sens(r_HD= r_HD, r_HS = r_HS, r_SD = r_SD,cycle=1/365) %>% \n  filter(method==\"P_st\") \n\nres_60yst_daily %>% \n  select(cycle,Healthy,Sick,Dead,life_exp) %>% \n  gt::gt() %>% \n  sub_missing(missing_text=\"-\") %>% \n  fmt_number(columns = c(Healthy,Sick,Dead,life_exp),decimals=1) %>% \n  cols_label(\"life_exp\" = \"Life Expectancy\")\n```\n\n::: {#fig-60y-st-daily .cell-output-display}\n```{=html}\n<div id=\"fqczstisrm\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>html {\n  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n}\n\n#fqczstisrm .gt_table {\n  display: table;\n  border-collapse: collapse;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#fqczstisrm .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#fqczstisrm .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#fqczstisrm .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#fqczstisrm .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 0;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#fqczstisrm .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fqczstisrm .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#fqczstisrm .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#fqczstisrm .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#fqczstisrm .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#fqczstisrm .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#fqczstisrm .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#fqczstisrm .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#fqczstisrm .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#fqczstisrm .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#fqczstisrm .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#fqczstisrm .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#fqczstisrm .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fqczstisrm .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#fqczstisrm .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#fqczstisrm .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fqczstisrm .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#fqczstisrm .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#fqczstisrm .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fqczstisrm .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fqczstisrm .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#fqczstisrm .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#fqczstisrm .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fqczstisrm .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#fqczstisrm .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-left: 4px;\n  padding-right: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fqczstisrm .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#fqczstisrm .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fqczstisrm .gt_left {\n  text-align: left;\n}\n\n#fqczstisrm .gt_center {\n  text-align: center;\n}\n\n#fqczstisrm .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#fqczstisrm .gt_font_normal {\n  font-weight: normal;\n}\n\n#fqczstisrm .gt_font_bold {\n  font-weight: bold;\n}\n\n#fqczstisrm .gt_font_italic {\n  font-style: italic;\n}\n\n#fqczstisrm .gt_super {\n  font-size: 65%;\n}\n\n#fqczstisrm .gt_footnote_marks {\n  font-style: italic;\n  font-weight: normal;\n  font-size: 75%;\n  vertical-align: 0.4em;\n}\n\n#fqczstisrm .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#fqczstisrm .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#fqczstisrm .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#fqczstisrm .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#fqczstisrm .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#fqczstisrm .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\">\n  \n  <thead class=\"gt_col_headings\">\n    <tr>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"cycle\">cycle</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Healthy\">Healthy</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Sick\">Sick</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Dead\">Dead</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Life Expectancy\">Life Expectancy</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"cycle\" class=\"gt_row gt_right\">21900</td>\n<td headers=\"Healthy\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"Sick\" class=\"gt_row gt_right\">42.6</td>\n<td headers=\"Dead\" class=\"gt_row gt_right\">957.4</td>\n<td headers=\"life_exp\" class=\"gt_row gt_right\">21.7</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n\nDaily Cycle\n:::\n:::\n\n\nBy switching to a daily cycle we now have 42.6 recorded as being in the sick state after 60 years (=21,900 days) and life expectancy is 21.7 years.\n\n### Signs of Trouble\n\nLet's recap what we have found after introducing background mortality as a competing risk:\n\n-   Using a **1-year cycle length**, life expectancy is 22.11 years.\n-   Using a **daily cycle length**, life expectancy is 21.73 years.\n\nThe only difference above is the cycle length used, yet we obtain a 0.38 year difference in life expectancy. What causes this difference?\n\n### Discretizing a Continuous Time Process\n\nThe answer boils down to the fact that with longer cycle lengths we \"hide\" some deaths that occur because a full healthy {{< fa arrow-right >}} sick {{< fa arrow-right >}} dead transition occurs within a single cycle.\n\nWhen we use the standard rate-to-probability conversion formula (i.e., $p_{HS}= 1 - e^{-r_{HS}\\Delta t}$) we obtain the *marginal* probability of transition. This marginal probability reflects the union of *all possible transitions* that start Healthy and then transition to and from the sick state in the cycle.\n\nThat is, $p_{HS}= 1 - e^{-r_{HS}\\Delta t}$ captures the probability of following scenarios occurring in a cycle:\n\n1.  Individual transitions from healthy to sick.\n2.  Individual transitions from healthy to sick to dead.\n\nBy including case 2 in the healthy {{< fa arrow-right >}} sick transition probability, we effectively rule out the possibility of becoming sick and dying within the same cycle. This implicit assumption means that we are no longer modeling a continuous time process, since we effectively \"hide\" some (quick) deaths that occur within a cycle due to the disease:\n\n\n```{dot}\n//| fig-align: center\n//| fig-width: 4\n//| fig-cap: compound Transition Patterns Using Standard Rate to Probability Conversion Formulas\n//| label: fig-comp-st\ndigraph G {\n    layout = neato;\n    Healthy [pos=\"0,0!\" style=\"filled\" fillcolor=\"#81aede\"];\n    Sick [pos=\"1,1!\" style=\"filled\" fillcolor=\"#81aede\"]; \n    Dead [pos=\"1,-1!\"]\n    Healthy -> Healthy [color=\"#d9d0d0\"];\n    Sick -> Sick [color=\"#d9d0d0\"];\n    Healthy -> Sick [color=\"blue\" penwidth=3 ]; \n    Sick -> Dead [color=\"red\" style=\"dotted\" penwidth=3];\n    Healthy -> Dead [color=\"#d9d0d0\"];\n    Dead -> Dead [color=\"#d9d0d0\"];\n  }\n```\n\n\nIn @fig-comp-st, and using standard rate-to-probability conversion formulas, the recorded states of a healthy {{< fa arrow-right >}} sick {{< fa arrow-right >}} dead transition are recorded in blue; the \"hidden\" transition is shown in red.\n\n#### Alternative Rate-to-Probability Conversion\n\nAnother set of formulas often used to account for competing risks are as follows:\n\n$$\np_{HS}= \\frac{r_{HS}}{r_{HS}+r_{HD}}\\big ( 1 - e^{-(r_{HS}+r_{HD})\\Delta t}\\big )\n$$\n\n$$\np_{HD}= \\frac{r_{HD}}{r_{HS}+r_{HD}}\\big ( 1 - e^{-(r_{HS}+r_{HD})\\Delta t}\\big )\n$$\n\n$$\np_{HH} = e^{-(r_{HS}+r_{HD})\\Delta t}\n$$\n\nLet's now use these formulas instead.\n\n@fig-m_P-cr shows the corresponding transition probability matrix:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nr_HD <- 0.006\nr_SD <- 10*0.006\n\nget_P(r_HS=r_HS,r_HD=r_HD,r_SD=r_SD,cycle=cycle) %>% \nfilter(name==\"P_cr\") %>% \nselect(-name) %>% \n#column_to_rownames(\"from\") %>% \nmutate_at(vars(-from), ~round(.,4)) %>% \ngt() %>% \n  cols_label(\"from\"=\"\")\n```\n\n::: {#fig-m_P-cr .cell-output-display}\n```{=html}\n<div id=\"gqssspegsh\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>html {\n  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n}\n\n#gqssspegsh .gt_table {\n  display: table;\n  border-collapse: collapse;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#gqssspegsh .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#gqssspegsh .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#gqssspegsh .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#gqssspegsh .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 0;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#gqssspegsh .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gqssspegsh .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#gqssspegsh .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#gqssspegsh .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#gqssspegsh .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#gqssspegsh .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#gqssspegsh .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#gqssspegsh .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#gqssspegsh .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#gqssspegsh .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#gqssspegsh .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#gqssspegsh .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#gqssspegsh .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gqssspegsh .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#gqssspegsh .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#gqssspegsh .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gqssspegsh .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#gqssspegsh .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#gqssspegsh .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gqssspegsh .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gqssspegsh .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#gqssspegsh .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#gqssspegsh .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gqssspegsh .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#gqssspegsh .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-left: 4px;\n  padding-right: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gqssspegsh .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#gqssspegsh .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gqssspegsh .gt_left {\n  text-align: left;\n}\n\n#gqssspegsh .gt_center {\n  text-align: center;\n}\n\n#gqssspegsh .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#gqssspegsh .gt_font_normal {\n  font-weight: normal;\n}\n\n#gqssspegsh .gt_font_bold {\n  font-weight: bold;\n}\n\n#gqssspegsh .gt_font_italic {\n  font-style: italic;\n}\n\n#gqssspegsh .gt_super {\n  font-size: 65%;\n}\n\n#gqssspegsh .gt_footnote_marks {\n  font-style: italic;\n  font-weight: normal;\n  font-size: 75%;\n  vertical-align: 0.4em;\n}\n\n#gqssspegsh .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#gqssspegsh .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#gqssspegsh .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#gqssspegsh .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#gqssspegsh .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#gqssspegsh .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\">\n  \n  <thead class=\"gt_col_headings\">\n    <tr>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"\"></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Healthy\">Healthy</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Sick\">Sick</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Dead\">Dead</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"from\" class=\"gt_row gt_left\">Healthy</td>\n<td headers=\"Healthy\" class=\"gt_row gt_right\">0.8556</td>\n<td headers=\"Sick\" class=\"gt_row gt_right\">0.1389</td>\n<td headers=\"Dead\" class=\"gt_row gt_right\">0.0056</td></tr>\n    <tr><td headers=\"from\" class=\"gt_row gt_left\">Sick</td>\n<td headers=\"Healthy\" class=\"gt_row gt_right\">0.0000</td>\n<td headers=\"Sick\" class=\"gt_row gt_right\">0.9418</td>\n<td headers=\"Dead\" class=\"gt_row gt_right\">0.0582</td></tr>\n    <tr><td headers=\"from\" class=\"gt_row gt_left\">Dead</td>\n<td headers=\"Healthy\" class=\"gt_row gt_right\">0.0000</td>\n<td headers=\"Sick\" class=\"gt_row gt_right\">0.0000</td>\n<td headers=\"Dead\" class=\"gt_row gt_right\">1.0000</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n\nTransition Probability Matrix Using Alternative Rate-to-Probability Conversion Formulas\n:::\n:::\n\n\nComparing @fig-m_P-st and @fig-m_P-cr, notice that a few things have changed. First, the probability of Healthy {{< fa arrow-right >}} Sick transition declined. This would seem to be consistent with a world in which there are fewer alive sick individuals observed at the end of the cycle--which we would expect if acute illness results in a nontrivial number of quick deaths after illness onset in a cycle.\n\nHowever, look at the Healthy {{< fa arrow-right >}} Dead transition probability change; **it went down, too**. If we were recording more acute deaths from the disease, we should see *more* Healthy {{< fa arrow-right >}} Dead transitions from individuals sojourning through the Sick state on their way to death in a single cycle.\n\nWhat about state occupancy and life expectancy under different cycle lengths?\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nres_60yst_cr <- \n  check_sens(r_HD= r_HD, r_HS = r_HS, r_SD = r_SD, cycle=1) %>% \n  filter(method==\"P_cr\") %>% \n  mutate(cycle = \"1y\") %>% \n  mutate(cycle_t = 60)\n\nres_60yst_daily_cr <- \n  check_sens(r_HD= r_HD, r_HS = r_HS, r_SD = r_SD,cycle=1/365) %>% \n  filter(method==\"P_cr\") %>% \n  mutate(cycle_t = cycle) %>% \n  mutate(cycle = \"Daily\")\n\nres_60yst_cr %>% \n  bind_rows(res_60yst_daily_cr) %>% \n  select(cycle,cycle_t,Healthy,Sick,Dead,life_exp) %>% \n  gt::gt() %>% \n  sub_missing(missing_text=\"-\") %>% \n  fmt_number(columns = c(Healthy,Sick,Dead,life_exp),decimals=1) %>% \n  cols_label(\"life_exp\" = \"Life Expectancy\")\n```\n\n::: {#fig-st-cr .cell-output-display}\n```{=html}\n<div id=\"gavydgqvae\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>html {\n  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n}\n\n#gavydgqvae .gt_table {\n  display: table;\n  border-collapse: collapse;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#gavydgqvae .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#gavydgqvae .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#gavydgqvae .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#gavydgqvae .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 0;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#gavydgqvae .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gavydgqvae .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#gavydgqvae .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#gavydgqvae .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#gavydgqvae .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#gavydgqvae .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#gavydgqvae .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#gavydgqvae .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#gavydgqvae .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#gavydgqvae .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#gavydgqvae .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#gavydgqvae .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#gavydgqvae .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gavydgqvae .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#gavydgqvae .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#gavydgqvae .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gavydgqvae .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#gavydgqvae .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#gavydgqvae .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gavydgqvae .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gavydgqvae .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#gavydgqvae .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#gavydgqvae .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gavydgqvae .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#gavydgqvae .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-left: 4px;\n  padding-right: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gavydgqvae .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#gavydgqvae .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gavydgqvae .gt_left {\n  text-align: left;\n}\n\n#gavydgqvae .gt_center {\n  text-align: center;\n}\n\n#gavydgqvae .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#gavydgqvae .gt_font_normal {\n  font-weight: normal;\n}\n\n#gavydgqvae .gt_font_bold {\n  font-weight: bold;\n}\n\n#gavydgqvae .gt_font_italic {\n  font-style: italic;\n}\n\n#gavydgqvae .gt_super {\n  font-size: 65%;\n}\n\n#gavydgqvae .gt_footnote_marks {\n  font-style: italic;\n  font-weight: normal;\n  font-size: 75%;\n  vertical-align: 0.4em;\n}\n\n#gavydgqvae .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#gavydgqvae .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#gavydgqvae .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#gavydgqvae .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#gavydgqvae .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#gavydgqvae .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\">\n  \n  <thead class=\"gt_col_headings\">\n    <tr>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"cycle\">cycle</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"cycle_t\">cycle_t</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Healthy\">Healthy</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Sick\">Sick</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Dead\">Dead</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Life Expectancy\">Life Expectancy</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"cycle\" class=\"gt_row gt_left\">1y</td>\n<td headers=\"cycle_t\" class=\"gt_row gt_right\">60</td>\n<td headers=\"Healthy\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"Sick\" class=\"gt_row gt_right\">43.9</td>\n<td headers=\"Dead\" class=\"gt_row gt_right\">956.0</td>\n<td headers=\"life_exp\" class=\"gt_row gt_right\">22.2</td></tr>\n    <tr><td headers=\"cycle\" class=\"gt_row gt_left\">Daily</td>\n<td headers=\"cycle_t\" class=\"gt_row gt_right\">21900</td>\n<td headers=\"Healthy\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"Sick\" class=\"gt_row gt_right\">42.6</td>\n<td headers=\"Dead\" class=\"gt_row gt_right\">957.4</td>\n<td headers=\"life_exp\" class=\"gt_row gt_right\">21.7</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n\n1-Year vs. Daily Cycle\n:::\n\n```{.r .cell-code  code-fold=\"true\"}\ndiff_st_cr <- \n  res_60yst_cr %>% \n    bind_rows(res_60yst_daily_cr) %>% mutate(life_exp = life_exp-lead(life_exp)) %>% pull(life_exp) %>% na.omit() %>% as.vector()\n```\n:::\n\n\nAgain, we have a difference in life expectancy of 0.462 years. *So switching to the alternative formulas has not fundamentally solved our problem.*\n\n#### How do transition probabilities change as the Likelihood of Disease-related death varies?\n\nAnother way to see the issue is to plot how the transition probabilities change (or not) at different levels of disease acuity. @fig-acuity-comparison-1y plots the relevant transition probabilities under a yearly time cycle, and while allowing the underlying hazard rate of death from the disease (`hr_S`) to vary.\n\nAs the hazard rate increases, the likelihood of ending up dead within a given cycle increases. Indeed, in the most extreme case, imagine the disease has a near instantaneous death rate. In that case we should see almost no Healthy {{< fa arrow-right >}} Sick transitions within a yearly cycle, because nearly everyone who became sick within the cycle died within 1 day.\n\nWe see in @fig-acuity-comparison-1y that the Healthy {{< fa arrow-right >}} Sick probabilities remain flat for transitions under which background mortality is a competing event. However, the Sick {{< fa arrow-right >}} Dead transition probabilities rise as the likelihood of fatal disease increases.\n\n\n::: {.cell .column-page}\n\n```{.r .cell-code  code-fold=\"true\"}\n1:10 %>% map(~get_P(r_HS=.15,r_HD=.006,r_SD=.006*.x,cycle=1) %>% mutate(hr_S=.x)) %>% \n  bind_rows() %>% \n  gather(transition,value,-from,-name,-hr_S) %>% \n  spread(name,value) %>% \n  filter(P_cr!=1 & P_cr!=0) %>% \n  gather(method,value,-from,-hr_S,-transition) %>% \n    filter(method!=\"P_eQ\") %>% \n  tibble() %>% \n  mutate_at(vars(transition), function(x) factor(x,levels=c(\"Healthy\",\"Sick\",\"Dead\"))) %>% \n  mutate_at(vars(from), function(x) factor(x,levels=c(\"Healthy\",\"Sick\",\"Dead\"),\n                                           labels=c(\"Healthy\",\"Sick\",\"Dead\"))) %>% \n  filter(from!=transition) %>% \n  ggplot(aes(x = hr_S, y = value)) + \n  geom_point(aes(colour=method, shape=method),size=3) + \n  scale_shape_manual(values = c(19,17)) +\n  scale_color_manual(values= c(\"blue\",\"red\")) +\n  facet_wrap(from~transition, scales=\"free\") + \n  ggthemes::theme_base() + \n  scale_x_continuous(expand = expansion(mult=.5))+\n  scale_y_continuous(expand = expansion(mult=.5))+\n  theme(legend.position = \"bottom\") +\n  directlabels::geom_dl(aes(label = glue::glue(\"  {method}\")), method=\"last.bumpup\",hjust=1) + \n  labs(x = \"hr_S (Hazard Ratio for Sick-to-Dead)\",y = \"Value\")\n```\n\n::: {.cell-output-display}\n![Yearly Cycle - Transition Probabilities by Sick-to-Dead Hazard Rate (P_st uses standard conversion formula; P_cr uses the formula that accounts for competing risks.)](embedding-a-transition-probability-matrix_files/figure-html/fig-acuity-comparison-1y-1.png){#fig-acuity-comparison-1y width=1152}\n:::\n:::\n\n\nIt is common practice to address these issues using the following guidelines:\n\n-   Select a cycle length where the probability of remaining in a given state is at least 95%.\n-   Pick a cycle length that aligns with the clinical/disease timelines of the decision problem.\n    -   Treatment schedules.\n    -   Acute vs. chronic condition.\n\nBut do these actually solve the issue? No. @fig-acuity-comparison-daily shows how the transition probabilities change when we switch to a *daily* cycle length. Again, we see the problem: as disease acuity increases, the probability of a Healthy {{< fa arrow-right >}} Dead transition does not change; **even though we shortened the cycle length, we have not fundamentally addressed the issue.**\n\n\n::: {.cell .column-page}\n\n```{.r .cell-code  code-fold=\"true\"}\n1:10 %>% map(~get_P(r_HS=.15,r_HD=.006,r_SD=.006*.x,cycle=1/365) %>% mutate(hr_S=.x)) %>% \n  bind_rows() %>% \n  gather(transition,value,-from,-name,-hr_S) %>% \n  spread(name,value) %>% \n  filter(P_cr!=1 & P_cr!=0) %>% \n  gather(method,value,-from,-hr_S,-transition) %>% \n  filter(method!=\"P_eQ\") %>% \n  tibble() %>% \n  mutate_at(vars(transition), function(x) factor(x,levels=c(\"Healthy\",\"Sick\",\"Dead\"))) %>% \n  mutate_at(vars(from), function(x) factor(x,levels=c(\"Healthy\",\"Sick\",\"Dead\"),\n                                           labels=c(\"Healthy\",\"Sick\",\"Dead\"))) %>% \n  filter(from!=transition) %>% \n  ggplot(aes(x = hr_S, y = value)) + \n  geom_point(aes(colour=method, shape=method),size=3) + \n    scale_shape_manual(values = c(19,17)) +\n  scale_color_manual(values= c(\"blue\",\"red\")) +\n  facet_wrap(from~transition, scales=\"free\") + \n  ggthemes::theme_base() + \n  scale_x_continuous(expand = expansion(mult=.5))+\n  scale_y_continuous(expand = expansion(mult=.5))+\n  theme(legend.position = \"bottom\") +\n  directlabels::geom_dl(aes(label = glue::glue(\"  {method}\")), method=\"last.bumpup\",hjust=1) + \n  labs(x = \"hr_S (Hazard Ratio for Sick-to-Dead)\",y = \"Value\")\n```\n\n::: {.cell-output-display}\n![Daily Cycle - Transition Probabilities by Sick-to-Dead Hazard Rate (P_st uses standard conversion formula; P_cr uses the formula that accounts for competing risks.)](embedding-a-transition-probability-matrix_files/figure-html/fig-acuity-comparison-daily-1.png){#fig-acuity-comparison-daily width=1152}\n:::\n:::\n\n\nHow does this all translate into model outputs, such as life expectancy? @fig-le-st plots life-expectancy (y-axis) against the underlying disease hazard rate for death. Each line provides the life-expectancy curve under a different cycle length, with everything else in the model held fixed.\n\nNot surprisingly, we see that as the likelihood of fatal disease increases, life expectancy declines.\n\nBut the most important takeaway is that the modeled life expectancy differs *depending on the cycle length used.* For a given hazard rate the underlying disease process is *exactly the same* -- but we get different answers depending on our cycle length.\n\nThe pattern of results is instructive, too. Essentially, with longer cycle lengths and incorrect transition probabilities, we will \"miss\" more compound within-cycle Healthy {{< fa arrow-right >}} Sick {{< fa arrow-right >}} Dead transitions and instead record them as Healthy {{< fa arrow-right >}} Sick transitions. This has a net effect of \"hiding\" more disease-related death in our model -- and life-expectancy is inflated as a result.\n\n\n::: {.cell .column-page meassage='false'}\n::: {.cell-output-display}\n![Life Expectancy by Sick-to-Dead Hazard Rate and Cycle Length. The left panel uses the formula that accounts for competing risks. The right panel uses standard conversion formula.](embedding-a-transition-probability-matrix_files/figure-html/fig-le-st-1.png){#fig-le-st width=960}\n:::\n:::\n\n\n# Act III: Embedding a Transition Matrix and Recording Events\n\nTo properly account for compound transitions that can occur due to competing risks, we need to do the following:\n\n1.  Embed the transition probability matrix by exponentiating the underlying transition rate matrix.\n2.  Include non-Markovian accumulators in the transition probability matrix. This facilitates accurately calculating model outputs (e.g., total costs, QALYs, etc.).\n\n## 1. Embed the Transition Probability Matrix\n\nOur rate matrix `Q` is constructed by including the relevant transition rates in the off-diagonal cells. The diagonal of `Q` is the negative sum of off-diagonal elements in the same row:\n\n|         | Healthy                | Sick                     | Dead                  |\n|------------------|------------------|-------------------|------------------|\n| Healthy | -($r_{HS}$ + $r_{HD}$) | $r_{HS}$                 | $r_{HD}$              |\n| Sick    | 0                      | -($hr_{S} \\cdot r_{HD}$) | $hr_{S} \\cdot r_{HD}$ |\n| Dead    | 0                      | 0                        | 0                     |\n\nHere is the rate matrix for the Healthy-Sick-Dead model:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nparams <- \n  list(r_HS = 0.15,\n       r_HD = 0.006,\n       hr_S = 10,\n       cycle = 1)\n\nQ <- \n  with(params,{\n    matrix(\n    c(-(r_HS*cycle+r_HD*cycle),r_HS*cycle,r_HD*cycle,\n      0,-r_SD*cycle,r_SD*cycle,\n      0,0,0),\n      nrow=3,\n      ncol=3,\n      byrow=TRUE,\n    dimnames = list(c(\"Healthy\",\"Sick\",\"Dead\"), c(\"Healthy\",\"Sick\",\"Dead\"))\n  ) \n  })\nQ\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n        Healthy  Sick  Dead\nHealthy  -0.156  0.15 0.006\nSick      0.000 -0.06 0.060\nDead      0.000  0.00 0.000\n```\n:::\n:::\n\n\nWe next embed the transition probability matrix `P` by taking the matrix exponential of `Q`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(expm)\nP <- expm(Q)\nP\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n          Healthy      Sick        Dead\nHealthy 0.8555592 0.1346958 0.009744961\nSick    0.0000000 0.9417645 0.058235466\nDead    0.0000000 0.0000000 1.000000000\n```\n:::\n:::\n\n\nAn alternative way of exponentiating a matrix is to perform a Taylor series expansion:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Identity matrix with same dimensions and names as Q \nQ_I <- diag(3)\ndimnames(Q_I) = dimnames(Q)\n\n# Note the %^% operator is in the expm package. \n\nQ2 = Q %^% 2   # Q-squared\nQ3 = Q %^% 3   # Q-cubed\nQ4 = Q %^% 4   # etc.\n\nQ_I + Q + (1/factorial(2))*Q2 + (1/factorial(3))*Q3 + (1/factorial(4))*Q4 \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n          Healthy      Sick        Dead\nHealthy 0.8555599 0.1346947 0.009745373\nSick    0.0000000 0.9417645 0.058235460\nDead    0.0000000 0.0000000 1.000000000\n```\n:::\n:::\n\n\nHow does this approach (`P_eQ`) perform relative to the other transition probability matrices (`P_st` and `P_cr`)? @fig-acuity-comparison-1y-embedded shows how the transition probabilities vary by hazard rate.\n\nWe can now see we've achieved what we need: Healthy {{< fa arrow-right >}} Dead transition probabilities that rise as the hazard rate of death from disease increases. Again, this occurs because as the likelihood of death after becoming ill increases, we increase the likelihood of a compound Healthy {{< fa arrow-right >}} Sick {{< fa arrow-right >}} Dead transition within a cycle. We need these to be recorded (accurately) as Healthy {{< fa arrow-right >}} Dead transitions, rather than Healthy {{< fa arrow-right >}} Sick transitions. Correspondingly, as the probability of a compound transition increases with an increasing hazard rate, the probability of a single Healthy {{< fa arrow-right >}} Sick transition declines; we see this in @fig-acuity-comparison-1y-embedded as well.\n\n\n::: {.cell .column-page}\n\n```{.r .cell-code  code-fold=\"true\"}\n1:10 %>% map(~get_P(r_HS=.15,r_HD=.006,r_SD=.006*.x,cycle=1) %>% mutate(hr_S=.x)) %>% \n  bind_rows() %>% \n  gather(transition,value,-from,-name,-hr_S) %>% \n  spread(name,value) %>% \n  filter(P_cr!=1 & P_cr!=0) %>% \n  gather(method,value,-from,-hr_S,-transition) %>% \n  #filter(method!=\"P_eQ\") %>% \n  tibble() %>% \n  mutate_at(vars(transition), function(x) factor(x,levels=c(\"Healthy\",\"Sick\",\"Dead\"))) %>% \n  mutate_at(vars(from), function(x) factor(x,levels=c(\"Healthy\",\"Sick\",\"Dead\"),\n                                           labels=c(\"Healthy\",\"Sick\",\"Dead\"))) %>% \n  filter(from!=transition) %>% \n  ggplot(aes(x = hr_S, y = value)) + \n  geom_point(aes(colour=method, shape=method),size=3) + \n  scale_shape_manual(values = c(19,17,3)) +\n  facet_wrap(from~transition, scales=\"free\") + \n  ggthemes::theme_base() + \n  scale_x_continuous(expand = expansion(mult=.5))+\n  scale_y_continuous(expand = expansion(mult=.5))+\n  theme(legend.position = \"bottom\") +\n  scale_color_manual(values= c(\"blue\",\"darkgreen\",\"red\")) +\n  directlabels::geom_dl(aes(label = glue::glue(\"  {method}\")), method=\"last.bumpup\",hjust=1) + \n  labs(x = \"hr_S (Hazard Ratio for Sick-to-Dead)\",y = \"Value\")\n```\n\n::: {.cell-output-display}\n![1-Year Cycle - Transition Probabilities by Sick-to-Dead Hazard Rate (P_st uses standard conversion formula; P_cr uses the formula that accounts for competing risks, and P_eQ is embedded using the transition rate matrix Q.)](embedding-a-transition-probability-matrix_files/figure-html/fig-acuity-comparison-1y-embedded-1.png){#fig-acuity-comparison-1y-embedded width=1152}\n:::\n:::\n\n\nWe also see that regardless of the cycle length used, we always end up with the same calculated life expectancy:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Life Expectancy by Sick-to-Dead Hazard Rate and Cycle Length](embedding-a-transition-probability-matrix_files/figure-html/fig-le-eQ-1.png){#fig-le-eQ width=672}\n:::\n:::\n\n\nWe have thus \"fixed\" our problem of hidden disease-related deaths!\n\n### Why is this important?\n\nThe use of an embedded transition probability matrix is important for a number of reasons:\n\n1.  The Markov model accurately reflects the underlying continuous time process.\n2.  We get an accurate accounting of disease-related deaths.\n3.  We can use whatever cycle length we need -- this facilitates computationally intensive processes such as probabilistic sensitivity analyses, which may not be feasible with a short (e.g., daily) cycle length.\n4.  We also avoid \"state explosion\" in the event our model has tunnel states. For example, if there is a one-year tunnel state for costs or utilities following disease onset, if we switched to a monthly or daily cycle we'd have to build in dozens or more health states into our Markov model. Beacuse we can stick with a one-year cycle, this makes use of tunnel states much more feasible.\n\nThe primary \"cost\" of using this approach over standard rate-to-probability conversion formulas is that we must be a bit more careful in structuring our transition probability matrix to include accumulators used to aggregate model outputs. We will cover this process in the section directly below.\n\n## 2. Include Non-Markovian Accumulators to Record Event Transitions\n\nWe now have the correct transition probabilities to model the underlying continuous-time process, but how do we account for these compound transitions in our aggregation of model outputs?\n\nFundamentally, what we have now is a model that will correctly records the \"true\" number of deaths at the end of the cycle, because all the compound Healthy {{< fa arrow-right >}} Sick {{< fa arrow-right >}} Dead transitions are included in the Healthy {{< fa arrow-right >}} Dead transition probability.\n\nTo track the total number of transitions to Sick, we must augment our transition probability matrix with non-Markovian accumulators. This accumulator shows up as a purple edge in our model diagram below:\n\n\n```{dot}\ndigraph G {\n    layout = neato;\n    Healthy [pos=\"0,0!\" style=\"filled\" fillcolor=\"#81aede\"];\n    Sick [pos=\"1,1!\" ]; \n    Dead [pos=\"1,-1!\" style=\"filled\" fillcolor=\"#81aede\"]\n    Healthy -> Healthy [color=\"#d9d0d0\"];\n    Sick -> Sick [color=\"#d9d0d0\"];\n    Healthy -> Sick [color=\"purple\" penwidth=3 style=\"dashed\"]; \n    Sick -> Dead [color=\"#d9d0d0\" ];\n    Healthy -> Dead [color=\"blue\",penwidth=3];\n    Dead -> Dead [color=\"#d9d0d0\" ];\n  }\n```\n\n\nFortunately, accumulators are easy to build in. We simply add the relevant transition rate in a new column in the transition rate matrix `Q`, *while leaving everything else the same.*\n\nSuppose we want to count up all the Healthy {{< fa arrow-right >}} Sick transitions in the model. To do this we simply add the appropriate transition rate ($r_{HS}$) in as an accumulator column:\n\n|         | Healthy                | Sick                     | Dead                  | accHS    |\n|---------------|---------------|---------------|---------------|---------------|\n| Healthy | -($r_{HS}$ + $r_{HD}$) | $r_{HS}$                 | $r_{HD}$              | $r_{HS}$ |\n| Sick    | 0                      | -($hr_{S} \\cdot r_{HD}$) | $hr_{S} \\cdot r_{HD}$ | 0        |\n| Dead    | 0                      | 0                        | 0                     | 0        |\n| accHS   | 0                      | 0                        | 0                     | 0        |\n\nNote the following:\n\n-   An extra row of 0's was added so that we balance the matrix, and ensure that we do not lose (or create!) anyone who becomes Sick.\n-   We **did not** update the diagonal elements (i.e., the negative sum of transition rates); these stay the same as before.\n-   If we wanted to add additional accumulators, we can just expand the matrix with more columns and rows as needed.\n\nHere is the augmented transition rate matrix for our example:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nQ_ <- data.frame(Q)\nQ_[\"Healthy\",\"accHS\"] <- params$r_HS\nQ_[\"accHS\",\"accHS\"] <- 0\nQ_[is.na(Q_)] <- 0\nQ_ <- as.matrix(Q_)\nQ_ \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n        Healthy  Sick  Dead accHS\nHealthy  -0.156  0.15 0.006  0.15\nSick      0.000 -0.06 0.060  0.00\nDead      0.000  0.00 0.000  0.00\naccHS     0.000  0.00 0.000  0.00\n```\n:::\n:::\n\n\nWe next embed the transition probability matrix, as before:[Notice that the accumulator (`accHS`) value is identical to the Healthy {{< fa arrow-right >}} Sick transition probability we obtained using the alternative rate-to-probability conversion formula that accounted for competing risks (e.g., see @fig-m_P-cr).]{.aside}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nP_ <- expm(Q_)\nP_\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n          Healthy      Sick        Dead     accHS\nHealthy 0.8555592 0.1346958 0.009744961 0.1388854\nSick    0.0000000 0.9417645 0.058235466 0.0000000\nDead    0.0000000 0.0000000 1.000000000 0.0000000\naccHS   0.0000000 0.0000000 0.000000000 1.0000000\n```\n:::\n:::\n\n\nUsing the accumulator we can accurately count up how many individuals transition to the Sick state over our time horizon:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_trace <- \n  0:(horizon/cycle) %>% \n  map_df(~(c(1000,0,0,0) %*% (P_%^%.x) %>% data.frame()))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nm_trace[3,] %>% \n  round(.,2) %>% \n  rownames_to_column(var=\"cycle\") %>% \n  select(-cycle) %>% \n  kable() %>% \n  kableExtra::kable_styling()\n```\n\n::: {#fig-state-2y-emb .cell-output-display}\n<table class=\"table\" style=\"margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:right;\"> Healthy </th>\n   <th style=\"text-align:right;\"> Sick </th>\n   <th style=\"text-align:right;\"> Dead </th>\n   <th style=\"text-align:right;\"> accHS </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:right;\"> 731.98 </td>\n   <td style=\"text-align:right;\"> 242.09 </td>\n   <td style=\"text-align:right;\"> 25.93 </td>\n   <td style=\"text-align:right;\"> 257.71 </td>\n  </tr>\n</tbody>\n</table>\n\n\n\nState Occupancy after Two Years\n:::\n:::\n\n\nWe see in @fig-state-2y-emb that after 2 years, 257.7 people (out of 1,000) have become sick, which is slightly less than the 259 who became sick after 2 years in our world without death as a competing risk.[This, of course, makes sense, since there are a small number of people who die before they could become ill once we add background mortality to the model]{.aside} Moreover, we see that state occupancy in the `Sick` category is lower, at 242.1. This lower value reflects the fact some people had a compound transition *through* Sick and ended up dead in the same cycle. The difference (15.6) amounts to the total number of individual deaths we \"hid\" in the model when we used the incorrect rate-to-probability conversion formulas.\n",
    "supporting": [
      "embedding-a-transition-probability-matrix_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../../../site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"../../../site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}