---
title: "A Unified Framework for Decision Analysis"
subtitle: "The PAN-DA Framework"
self-contained: true
---

Decision analytic modeling methods have seen substantial growth in both complexity and scope---so much so that tackling any given decision problem requires that practitioners first work through an implicit "methodological decision tree" to guide decisions on various modeling approaches available for use (e.g., discrete time Markov, discrete event simulation, microsimulation, etc.).

This traditional "pathway" is envisioned in the figure below. The figure makes clear that the practitioner often starts with a **decision problem**--that is, research question that aims to quantify the cost and health impacts of a new health technology, treatment, policy, etc.

Based both on the expertise and training of the modeler, as well as the decision problem itself, a decision is made over which modeling approach to use: a deterministic, cohort-based approach (e.g., discrete time Markov) or Monte Carlo-based approach (e.g., discrete event simulation, microsimulation, etc.)

```{mermaid,fig-cap="Test"}

flowchart LR
    A["Decision Problem"] --> mt_micro[Microsimulation]
    A --> mt_markov[Markov]
    A --> mt_des[Discrete Event Simulation]
    mt_micro --> s_micro_r[R]
    mt_micro --> s_micro_o["Other\n(C++, Python, Treeage)"]
    mt_markov --> s_markov_r[R]
    mt_markov --> s_markov_e[Excel]
    mt_markov --> s_markov_o["Other\n(C++, Treeage)"]
    mt_des --> s_des_r[R]
    mt_des --> s_des_o["Other\n(C++, Python)"]
    s_micro_r --> p_micro_r>Parameterize]
    s_micro_o --> p_micro_o>Parameterize]
    s_markov_r --> p_markov_r>Parameterize]
    s_markov_e --> p_markov_e>Parameterize]
    s_markov_o --> p_markov_o>Parameterize]
    s_des_r --> p_des_r>Parameterize]
    s_des_o --> p_des_o>Parameterize]
    p_micro_r --> run_micro_r>Run]
    p_micro_o --> run_micro_o>Run]
    p_markov_r --> run_markov_r>Run]
    p_markov_e --> run_markov_e>Run]
    p_markov_o --> run_markov_o>Run]
    p_des_r --> run_des_r>Run]
    p_des_o --> run_des_o>Run]
    run_micro_r --> sum_micro_r>Summarize]
    run_micro_o --> sum_micro_o>Summarize]
    run_markov_r --> sum_markov_r>Summarize]
    run_markov_e --> sum_markov_e>Summarize]
    run_markov_o --> sum_markov_o>Summarize]
    run_des_r --> sum_des_r>Summarize]
    run_des_o --> sum_des_o>Summarize]

subgraph Model
 mt_micro & mt_markov & mt_des
end
subgraph Software
s_micro_r & s_micro_o & s_markov_r & s_markov_o & s_markov_e & s_des_r & s_des_o & s_markov_e
end
subgraph micro_r[" "]
p_micro_r & run_micro_r & sum_micro_r
end
subgraph micro_o [" "]
p_micro_o & run_micro_o & sum_micro_o
end
subgraph markov_r[" "]
p_markov_r & run_markov_r & sum_markov_r
end
subgraph markov_e[" "]
p_markov_e & run_markov_e & sum_markov_e
end
subgraph markov_o[" "]
p_markov_o & run_markov_o & sum_markov_o
end
subgraph des_r[" "]
p_des_r & run_des_r & sum_des_r
end
subgraph des_o[" "]
p_des_o & run_des_o & sum_des_o
end   
style Model fill:#e6e5e3,::
style Software fill:#e6e5e3,::
style micro_r fill:#a8daf0,::
style micro_o fill:#dcedf5,::
style des_r fill:#a3db8f,::
style des_o fill:#c7d9c1,::
style markov_r fill:#efdcf5,::
style markov_e fill:#b29eba,::
style markov_o fill:#f393fa,::

```

```{mermaid}
flowchart LR
    A["Decision Problem"] --> param_e
    param_e>"Parameterize\n(Excel or R)"] --> Rshiny(("RShiny/GUI"))
    Rshiny-->micro[Microsimulation]
    Rshiny-->markov[Markov]
    Rshiny-->des[Discrete Event Simulation]
    des-->run>Run]
    micro-->run
    markov-->run
    run-->summarize>Summarise]

subgraph rshiny["PAN-DA Framework"]
Rshiny & micro & markov & des & run & summarize
end
style rshiny fill:#fadea7,::
```
